flask_app/main/routes.py
from flask import render_template, request, current_app, Blueprint, redirect, url_for
from flask_app import db
import json
from flask_app.models import Question, User

main = Blueprint("main", __name__)


@main.route("/")
def index():
    questions = Question.query.all()[::-1]
    return render_template("index.html", title="Home", questions=questions)


@main.route("/about")
def about():
    return render_template("about.html", title="About")


@main.route("/user/<username>")
def user_detail(username):
    user = User.query.filter_by(username=username).first()

    questions=user.questions[::-1]
    answers=user.answers[::-1]
    comments=user.comments[::-1]

    print(questions)
    print(answers)
    print(comments)

    return render_template(
        "user_detail.html",
        user=user,
        questions=user.questions[::-1],
        answers=user.answers[::-1],
        comments=user.comments[::-1],
    )


@main.route("/csp_error_handling", methods=["POST"])
def report_handler():
    """
    Receives POST requests from the browser whenever the Content-Security-Policy
    is violated. Processes the data and logs an easy-to-read version of the message
    in your console.
    """
    report = json.loads(request.data.decode())["csp-report"]

    # current_app.logger.info(json.dumps(report, indent=2))

    violation_desc = "\nViolated directive: %s, \nBlocked: %s, \nOriginal policy: %s \n" % (
        report["violated-directive"],
        report["blocked-uri"],
        report["original-policy"]
    )

    current_app.logger.info(violation_desc)
    return redirect(url_for("main.index"))

flask_app/questions/routes.py
from flask import (
    render_template,
    url_for,
    redirect,
    request,
    Blueprint,
    session,
    current_app,
)
from flask_login import login_user, current_user, logout_user, login_required

from flask_app import db, bcrypt
from flask_app.models import User, Question, Answer, Comment
from flask_app.questions.forms import QuestionForm, AnswerForm, CommentForm, UpdateQuestionForm, UpdateAnswerForm

questions = Blueprint("questions", __name__)

@questions.route("/ask_question", methods=["GET", "POST"])
@login_required
def ask_question():
    form = QuestionForm()

    if form.validate_on_submit():

        question = Question(
            question=form.question.data,
            details=form.details.data,
            author=current_user,
        )

        db.session.add(question)
        db.session.commit()

        return redirect(url_for("main.index"))

    return render_template("ask_question.html", title="Ask a Question", form=form)


@questions.route("/questions/<question_id>", methods=["GET", "POST"])
def question_detail(question_id):
    answer_form = AnswerForm()
    comment_form = CommentForm()

    question = Question.query.filter_by(id=question_id).first()

    if answer_form.validate_on_submit():
        answer = Answer(
            answer=answer_form.answer.data,
            author=current_user,
            question=question,
            user_id=current_user.id
        )

        db.session.add(answer)
        db.session.commit()

        return redirect(request.path)

    if comment_form.validate_on_submit():
        answer = Answer.query.filter_by(id=comment_form.answerID.data).first()
        comment = Comment(
            comment=comment_form.comment.data,
            author=current_user,
            answer=answer,
            user_id=current_user.id
        )

        db.session.add(comment)
        db.session.commit()

        return redirect(request.path)

    answers = question.answers[::-1]
    num_answers = len(answers)
    user_answered = None
    if (current_user.is_authenticated):
        user_answered = any(answer.author.username == current_user.username for answer in answers)
    comments = []
    for answer in answers:
        comments.append(answer.comments[::-1])

    return render_template(
        "question_detail.html",
        question=question,
        answers_bundle=zip(answers, comments),
        num_answers=num_answers,
        answer_form=answer_form,
        comment_form=comment_form,
        user_answered=user_answered
    )


@questions.route("/update_question/<question_id>", methods=["GET", "POST"])
def update_question(question_id):
    form = UpdateQuestionForm()

    question = Question.query.filter_by(id=question_id).first()

    if form.validate_on_submit():
        question.question = form.question.data
        question.details = form.details.data
        db.session.commit()

        return redirect(url_for("questions.question_detail", question_id=question_id))

    return render_template("update_question.html", form=form, question=question)


@questions.route("/update_answer/<answer_id>", methods=["GET", "POST"])
def update_answer(answer_id):
    form = UpdateAnswerForm()

    answer = Answer.query.filter_by(id=answer_id).first()
    question = Question.query.filter_by(id=answer.question_id).first()

    if form.validate_on_submit():
        answer.answer = form.answer.data
        db.session.commit()

        return redirect(url_for("questions.question_detail", question_id=answer.question_id))

    return render_template("update_answer.html", form=form, question=question, answer=answer)
    

flask_app/users/routes.py
from flask import render_template, url_for, redirect, request, Blueprint, session, flash
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Mail, Message
from flask_app import db, bcrypt
from flask_app.models import User, Question
from flask_app.users.forms import RegistrationForm, LoginForm, UpdateUsernameForm, UpdateEmailForm, UpdatePasswordForm
from flask_app.users.token import generate_confirmation_token, confirm_token
from flask_app.users.email import send_email

import qrcode
import qrcode.image.svg as svg
import pyotp

from io import BytesIO

users = Blueprint("users", __name__)
mail = Mail()

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed, confirmed=False)
        db.session.add(user)
        db.session.commit()

        session['reg_username'] = user.username
        token = generate_confirmation_token(form.email.data)
        confirm_url = url_for('users.confirm_email', token=token)
        html = render_template('confirmation_email.html', user=user, confirm_url=confirm_url)
        subject = "Welcome to Ask.it!"
        send_email(user.email, subject, html)

        flash('A confirmation email has been sent via email.', 'success')
        return redirect(url_for('users.tfa', user=user))

    return render_template('register.html', form=form)

@users.route('/confirm/<token>')
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        if current_user.is_authenticated:
            return redirect(url_for('main.index'))
        else:
            return redirect(url_for('users.login'))
    else:
        user.confirmed = True
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return render_template('confirm_account.html')

@users.route("/tfa")
def tfa():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return render_template('tfa.html'), headers

@users.route("/qr_code")
def qr_code():
    if 'reg_username' not in session:
        return redirect(url_for('main.index'))

    user = User.query.filter_by(username=session['reg_username']).first()
    session.pop('reg_username')
    img = qrcode.make(user.get_auth_uri(), image_factory=svg.SvgPathImage)
    stream = BytesIO()
    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return stream.getvalue(), headers

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user is not None and user.confirmed == True and \
        bcrypt.check_password_hash(user.password, form.password.data) and form.otp.data == pyotp.TOTP(user.otp_secret).now():
            login_user(user)
            return redirect(url_for('main.index', username=form.username.data))

    return render_template('login.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    session['reg_username'] = current_user.username
    userForm = UpdateUsernameForm()
    emailForm = UpdateEmailForm()
    passwordForm = UpdatePasswordForm()
    print(request.form)
    if request.method == 'POST':
        if userForm.validate_on_submit():
            current_user.username = userForm.username.data
            db.session.commit()
            msg = Message("Updated Account Username",
                recipients=[current_user.email],
                body="Hello user at " + current_user.email + ", you have chosen to change your username to " + current_user.username + "."
                + "\nIf this was not you, please login to your account to change your account information.")
            mail.send(msg)
            return redirect(url_for('users.account'))
        elif emailForm.is_submitted() and emailForm.validate_on_submit():
            current_user.email = emailForm.email.data
            db.session.commit()
            html = render_template('update_email.html', username=current_user.username)
            subject = "Updated Email"
            send_email(current_user.email, subject, html)

            return redirect(url_for('users.account'))
        elif passwordForm.is_submitted() and passwordForm.validate_on_submit():
            hashed = bcrypt.generate_password_hash(passwordForm.new_password.data).decode('utf-8')
            user = User.query.filter_by(username=current_user.username).first()
            user.password = hashed
            db.session.commit()
            msg = Message("Updated Account Password",
                recipients=[current_user.email],
                body="Hello " + current_user.username + ", you have chosen to change your password." +
                "\nIf this was not you, please contact us to recover your account information.")
            mail.send(msg)
            logout_user()
            return redirect(url_for('users.login'))

    userForm.username.data = current_user.username
    emailForm.email.data = current_user.email
    return render_template('account.html', title='Account', userForm=userForm, emailForm=emailForm, passwordForm=passwordForm)

flask_app/templates/account.html
{% extends "base.html" %}
{% block content %}
<br>
<div>
    <h2>{{ current_user.username }}</h2>
    <p>Email: {{ current_user.email }}</p>
</div>
<div>
  <img src={{ url_for('users.qr_code') }} alt="QR Code for 2FA"><br>QR code for authenticator app to obtain login passcode
</div><br>
<a href={{ url_for('main.user_detail', username=current_user.username) }}>
    <h4>Click here to see all of your questions, answers, and comments!</h4>
</a>
<br>
<h3>Update Account Info</h4><br>
<article class="content-section">
<div class="list-group-item">
    <form action="" name="usernameForm" method="post">
       {{ userForm.csrf_token }}
       <div>
           {{ userForm.username.label(class="form-control-label") }}
           {{ userForm.username(class="form-control form-control-lg") }}

           {% if userForm.username.errors %}
           <div class="alert alert-warning" role="alert">
               {% for error in userForm.username.errors %}
                   <span>{{ error }}</span>
               {% endfor %}
           </div>
           {% endif %}
         </div>
       <div>
           <br>{{ userForm.submit(class="form-control form-control-lg") }}
       </div>
    </form>
</div>
<div class="list-group-item">
    <form action="" name="emailForm" method="post">
       {{ emailForm.csrf_token }}
       <div>
           {{ emailForm.email.label(class="form-control-label") }}
           <small>(Login and email confirmation is required after email update)</small>
           {{ emailForm.email(class="form-control form-control-lg") }}

           {% if emailForm.email.errors %}
           <div class="alert alert-warning" role="alert">
               {% for error in emailForm.email.errors %}
                   <span>{{ error }}</span>
               {% endfor %}
           </div>
           {% endif %}
         </div>
       <div>
          <br>{{ emailForm.submit(class="form-control form-control-lg") }}
       </div>
    </form>
</div>
<div class="list-group-item">
    <form action="" name="passwordForm" method="post">
       {{ passwordForm.csrf_token }}
       <div>
           {{ passwordForm.old_password.label(class="form-control-label") }}
           <small>(Login is required after password update)</small>
           {{ passwordForm.old_password(class="form-control form-control-lg") }}
		   {% if passwordForm.old_password.errors %}
           <div class="alert alert-warning" role="alert">
               {% for error in passwordForm.old_password.errors %}
                   <span>{{ error }}</span>
               {% endfor %}
           </div>
           {% endif %}
		   <br>{{ passwordForm.new_password.label(class="form-control-label") }}
        <small>(Login is required after password update)</small>
       <ul>
         <small><li>Password must be between 6 and 20 characters long</li>
         <li>Password must include at least 1 symbol</li>
         <li>Password must include at least 1 uppercase letter</li>
         <li>Password must include at least 1 number</li></small>
       </ul>
           {{ passwordForm.new_password(class="form-control form-control-lg") }}
		       {% if passwordForm.new_password.errors %}
           <div class="alert alert-warning" role="alert">
               {% for error in passwordForm.new_password.errors %}
                   <span>{{ error }}</span>
               {% endfor %}
           </div>
           {% endif %}
		   <br>{{ passwordForm.confirm_password.label(class="form-control-label") }}
       <small>(Login is required after password update)</small>
       {{ passwordForm.confirm_password(class="form-control form-control-lg") }}
		   {% if passwordForm.confirm_password.errors %}
           <div class="alert alert-warning" role="alert">
               {% for error in passwordForm.confirm_password.errors %}
                   <span>{{ error }}</span>
               {% endfor %}
           </div>
           {% endif %}
       <div>
           <br>{{ passwordForm.submit(class="form-control form-control-lg") }}
       </div>
    </form>
</div>
</article>
{% endblock %}

flask_app/templates/ask_question.html
{% extends "base.html" %}
{% block content %}
<div>
    <br><h2>Ask a Question!</h2><br>
</div>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.question.label(class="form-control-label") }}
            {{ form.question(class="form-control form-control-md") }}

            {% if form.question.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.question.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
			      <br>{{ form.details.label(class="form-control-label") }}
            {{ form.details(class="form-control form-control-md") }}

            {% if form.details.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.details.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
			<div><br>
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/base.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href={{ url_for('static', filename='css/custom.css') }}>

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Ask.it</title>
    {% endif %}
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">

            <a class="navbar-brand" href={{ url_for('main.index' )}}>Ask.it</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href={{ url_for('main.index') }} class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('main.about') }} class="nav-link">About</a>
                    </li>
                </ul>

                {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href={{ url_for('main.user_detail', username=current_user.username) }} class="nav-link">Logged in as: <b>{{ current_user.username }}</b></a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('questions.ask_question') }} class="nav-link">Ask a Question!</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.account' )}} class="nav-link">My Account</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.logout' )}} class="nav-link">Logout</a>
                    </li>
                </ul>

                {% else %}

                <ul class="nav navbar-nav ml-auto justify-content-end">
                    <li class="nav-item">
                        <a href={{ url_for('users.login' )}} class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href={{ url_for('users.register' )}} class="nav-link">Register</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>
    </header>

    <main class="container">
        <div class="row">
            <div class="col-md-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

flask_app/templates/index.html
{% extends "base.html" %}
{% block content %}
<br><div class="page-header">
    <div class="float-left">
      <h1>Questions</h1>
    </div>
    {% if current_user.is_authenticated %}
    <div class="float-right">
      <a href={{url_for('questions.ask_question')}}><button type="button" class="btn btn-primary"><h4>Ask a Question!<h4></button></a>
    </div>
    {% endif %}
     <div class="clearfix"></div>
</div><br>

<div class="list-group">
    {% for question in questions %}
    <div class="list-group-item">
        <div class="d-flex w-100 justify-content-between">
            <a href={{ url_for('questions.question_detail', question_id=question.id) }}>
                <h5 class="mb-1">{{ question.question }}</h5>
            </a>
            <small class="text-muted"><a href={{ url_for('questions.question_detail', question_id=question.id) }}>Comments</a>
				• <a href={{ url_for('main.user_detail', username=question.author.username) }}>{{ question.author.username }}</a>
                • {{ question.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
		</div>
		<p class="mb-1">{{ question.details }}</p>
	</div>
    {% endfor %}
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "base.html" %}
{% block content %}
<br><div>
    <h2>Log In</h2>
</div>
<div>
    If you <b>don't</b> have an account, then <a href={{ url_for('users.register') }}>Register!</a>
</div><br>
<div>
    <form action="" method="post">
        {{ form.csrf_token }}
        <div>
            {{ form.username.label(class="form-control-label") }}
            {{ form.username(class="form-control form-control-md") }}

            {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            {{ form.password.label(class="form-control-label") }}
            {{ form.password(class="form-control form-control-lg") }}
        </div>
		<div>
            {{ form.otp.label(class="form-control-label") }}
            {{ form.otp(class="form-control form-control-lg") }}
			{% if form.otp.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.otp.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div>
            <br>{{ form.submit(class="form-control form-control-lg") }}
        </div>
    </form>
</div>
{% endblock %}

flask_app/templates/question_detail.html
{% extends "base.html" %}
{% block content %}
<br><article class="content-section">
    <div class="list-group-item">
        <h1>{{ question.question }}</h1>
        <div>
            <small>
                <a href={{ url_for('main.user_detail', username=question.author.username) }}>
                    {{ question.author.username }}
                </a> • {{ question.date.strftime('%b %d, %Y at %I:%M %p') }}
            </small>
        </div>
		<br>
		<p><large>{{ question.details }}</large> </p>
		{% if current_user.id == question.user_id %}
		<div class="float-left">
			<a href={{ url_for('questions.update_question', question_id=question.id) }}>
				<button type="button" class="btn btn-primary">
					<small>Update Question</small>
				</button>
			</a>
		</div><br><br>
		{% endif %}
    </div>
</article>
{% if num_answers > 1 %}
	<br><h3>Answers</h3>
{% elif num_answers == 1 %}
  <br><h3>Answer</h3>
{% endif %}
{% if answers_bundle %}
  {% for answer, comments in answers_bundle %}
    <div class="list-group-item">
        <div class="d-flex w-100 justify-content-between">
            <a href={{ url_for('main.user_detail', username=answer.author.username) }}>
                <h5 class="mb-1">{{ answer.author.username }}</h5>
            </a>
            <small class="text-muted">{{ answer.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
        </div>
        <p><large>{{ answer.answer }}</large></p>
		{% if current_user.id == answer.user_id %}
		<div class="float-left">
			<a href={{ url_for('questions.update_answer', answer_id=answer.id) }}>
				<button type="button" class="btn btn-primary">
					<small>Update Answer</small>
				</button>
			</a>
		</div><br>
		{% endif %}
		<br>
		{% if comments %}
		<h5>Comments:</h5>
		<div class="list-group">
			{% for comment in comments %}
			<div class="list-group-item">
				<div class="d-flex w-100 justify-content-between">
					<a href={{ url_for('main.user_detail', username=comment.author.username) }}>
						<h5 class="mb-1">{{ comment.author.username }}</h5>
					</a>
					<small class="text-muted">{{ comment.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
				</div>
				<p class="mb-1">{{ comment.comment }}</p>
			</div>
			{% endfor %}
		</div>
		{% endif %}
        {% if current_user.is_authenticated %}
        <div id="comment_form">
            <form action="" method="post">
              {{comment_form.csrf_token}}
              <div>
                {{ comment_form.comment.label(class="form-control-label") }}
                {{ comment_form.comment(class="form-control form-control-lg") }}
                {{ comment_form.answerID(value=answer.id)}}
              </div>
              <div>
				{{ comment_form.submit(class="form-control form-control-lg") }}
              </div>
            </form>
        </div>
        {% endif %}
    </div>
    {% endfor %}
{% else %}
<br><h5>No answer yet... be the first! (Make sure you're logged in)</h5>
{% endif %}
<br>
{% if current_user.is_authenticated %}
	{% if not user_answered %}
	<div>
		<h3>Submit an answer!</h3>
		<form action="" method="post">
		  {{answer_form.csrf_token}}
		  <div>
			{{ answer_form.answer.label(class="form-control-label") }}
			{{ answer_form.answer(class="form-control form-control-lg") }}
		  </div>
		  <div>
			<br>{{ answer_form.submit(class="form-control form-control-lg") }}
		  </div>
		</form>
	</div>
	{% endif %}
{% endif %}
{% endblock %}

flask_app/templates/tfa.html
{% extends "base.html" %}
{% block content %}
    <br><div>
        <h2>Two-Factor Authentication</h2>
    </div>
    <div>
        This website requires mandatory 2FA enrollment.
    </div>
    <!-- Registration Form: -->
    <p>
        Use an authenticator app to enroll with us! You will need to use this app to login in the future.
    </p>
    <img src={{ url_for('users.qr_code') }} alt="QR Code for 2FA">

    <div>
        You will receieve an email to confirm your account before logging in.
        <br><a href={{ url_for('main.index') }}>Click here</a> to navigate back to the home page.
    </div>


{% endblock %}

flask_app/templates/update_answer.html
{% extends "base.html" %}
{% block content %}
<div>
    <br><h2>Update Answer</h2>
</div>
<br><article class="content-section">
    <div class="list-group-item"s>
        <h1>{{ question.question }}</h1>
        <div>
            <small>
                <a href={{ url_for('main.user_detail', username=question.author.username) }}>
                    {{ question.author.username }}
                </a> • {{ question.date.strftime('%b %d, %Y at %I:%M %p') }}
            </small>
        </div><br>
		    <p><large>{{ question.details }}</large> </p>
    </div><div class="list-group-item">
    <div class="d-flex w-100 justify-content-between">
        <a href={{ url_for('main.user_detail', username=answer.author.username) }}>
            <h5 class="mb-1">{{ answer.author.username }}</h5>
        </a>
        <small class="text-muted">{{ answer.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
    </div>
    <p class="mb-1">{{ answer.answer }}</p>
</div>
</article><br>
<div>
		<h3>Update Answer</h3>
		<form action="" method="post">
		  {{ form.csrf_token }}
		  <div>
			{{ form.answer.label(class="form-control-label") }}
			{{ form.answer(class="form-control form-control-lg") }}
		  </div>
		  <div>
			<br>{{ form.submit(class="form-control form-control-lg") }}
		  </div>
		</form>
	</div>
{% endblock %}

flask_app/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
<br><div class="col-md-12">
    <h1>{{ user.username }}'s History</h1>
</div><br>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Questions:</h3>
			{% if questions %}
            <br><div class="list-group">
                {% for question in questions %}
                <div class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <a href={{ url_for('questions.question_detail', question_id=question.id) }}>
                            <h5 class="mb-1">{{ question.question }}</h5>
                        </a>
                        <small class="text-muted"><a
                                href={{ url_for('questions.question_detail', question_id=question.id) }}>Comments</a>
                            • <a
                                href={{ url_for('main.user_detail', username=current_user.username) }}>{{ question.author.username }}</a>
                            • {{ question.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
                    </div>
					<p>{{ question.details }}</p>
                </div>
                {% endfor %}
            </div>
			{% else %}
			<a href={{ url_for('questions.ask_question') }}>
				<h5>No questions yet... click here to ask a question!</h5>
			</a>
			{% endif %}
        </div>
	</div>
	<br>
	<div class="row">
		<div class="col-md-6">
            <h3>Answers:</h3><br>
            <div class="list-group">
                {% for answer in answers %}
                <div class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">
                          <a href={{ url_for('questions.question_detail', question_id=answer.question.id) }}>{{ answer.question.question }}</a>
                        </h5>
                        <small class="text-muted">{{ answer.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
                    </div>
                    <p class="mb-1">{{ answer.answer }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            <h3>Comments:</h3><br>
            <div class="list-group">
                {% for comment in comments %}
                <div class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">
                          <a href={{ url_for('questions.question_detail', question_id=comment.answer.question.id) }}>{{ comment.answer.question.question }}</a>
                        </h5>
                        <small class="text-muted">{{ comment.date.strftime('%b %d, %Y at %I:%M %p') }}</small>
                    </div>
                    <p class="mb-1">{{ comment.comment }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div><br>
{% endblock %}